### ISSUE TITLE
Create a list of the "pages" that users can access (login, homepage, xxx, yyy etc)

### ISSUE THREAD

**Issue by adriant172** [adriant172/CS50_Final_Project#2]
- Registration
- Login
- Index/homepage
- Account Settings/Preferences
- Suggestions
- View Recipe
- General Search Results

**Comment by psyrus** [comment]
Your feature set states "share recipes", but where is that done? Does it not need aa page?

**Comment by psyrus** [comment]
Is the registration page where budgets are entered? How do they update their budget at a later time?

**Comment by adriant172** [comment]
> Your feature set states "share recipes", but where is that done? Does it not need aa page?

- I was thinking the share option could just be added to the view recipe page , however I will add it as its own page for now for the initial "bootstrapping" phase

**Comment by adriant172** [comment]
- task completed
