### ISSUE TITLE
Figure out what DATABASE schema(s) you would need to support the above functionality

### ISSUE THREAD

**Issue by adriant172** [adriant172/CS50_Final_Project#3]
possible Schema 
1. Users
        - ID , username, Preferences(Cuisine Tag IDs), Password Hash, points, Current Daily Budget, Favorites(Recipe IDs)

2. Cuisine Tags
         - ID, Cuisine Type( Origin or Type)

3. Recipes
          - ID, name, API reference ID, # of shares, # of ratings, current rating

**Comment by psyrus** [comment]
Your Recipes table doesn't have reference to a cuisine tag... how would you connect those?

**Comment by adriant172** [comment]
![image](https://user-images.githubusercontent.com/58478399/152688152-dca6c228-436b-4752-9857-ea518ed22453.png)

**Comment by adriant172** [comment]
- task completed
